"""Add parsed_text_path to Document

Revision ID: 284222c2f356
Revises: 1f3d45b86ab2
Create Date: 2026-05-24 13:42:48.270542

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "284222c2f356"
down_revision: str | None = "1f3d45b86ab2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("parsed_text_path", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "parsed_text_path")
    # ### end Alembic commands ###
