"""Add DocumentChunk table

Revision ID: a1a8742ef7fd
Revises: d2159b7d8b10
Create Date: 2026-05-24 17:13:38.033533

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a1a8742ef7fd"
down_revision: str | None = "d2159b7d8b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
