"""Add DocumentChunk table

Revision ID: d2159b7d8b10
Revises: 4e2b8a570c96
Create Date: 2026-05-24 16:57:55.505180

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d2159b7d8b10"
down_revision: str | None = "4e2b8a570c96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
